apiVersion: batch/v1
kind: CronJob
metadata:
  name: certbot-renewal
spec:
  schedule: "0 0 1 * *"  # Run every month
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: certbot
              image: certbot/certbot
              args:
                - "renew"
                - "--webroot"
                - "-w"
                - "/var/www/certbot"
          restartPolicy: OnFailure
