apiVersion: batch/v1
kind: Job
metadata:
  name: certbot-job
spec:
  template:
    spec:
      containers:
        - name: certbot
          image: certbot/certbot
          args:
            - "certonly"
            - "--webroot"
            - "-w"
            - "/var/www/certbot"
            - "-d"
            - "your-domain.com"
          volumeMounts:
            - name: certbot-webroot
              mountPath: /var/www/certbot
            - name: certbot-lets-encrypt
              mountPath: /etc/letsencrypt
      restartPolicy: OnFailure
  backoffLimit: 4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certbot-lets-encrypt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
