apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: portfolio:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Never
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007 # this is the port that will be exposed to the outside world
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    # This is required to proxy Grafana Live WebSocket connections.
    map $http_upgrade $connection_upgrade {
      default upgrade;
      '' close;
    }

    server {
        listen 80;
        server_name localhost;

        # Root directory for shared assets (images, CSS, JS, etc.)
        root /usr/share/nginx/html;

        # Default location for the site
        location / {
            index /en/index.html;
        }

        # Location for /en (to serve the index.html from /en directory)
        location /en/ {
            index /en/index.html;
        }

        # Location for /fr (to serve the index.html from /fr directory)
        location /fr/ {
            index /fr/index.html;
        }

        location /stub_status {
            stub_status on;
            access_log off;
        }

        location /grafana/ {
            proxy_pass         http://grafana.default.svc.cluster.local:3000/;
            rewrite  ^/grafana/(.*)  /$1 break;
            proxy_set_header   Host $host;
        }
        
        # Proxy Grafana Live WebSocket connections.
        location /grafana/api/live/ {
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection $connection_upgrade;
          proxy_set_header Host $host;
          proxy_pass http://grafana.default.svc.cluster.local:3000/;
          rewrite  ^/grafana/(.*)  /$1 break;
        }
    }