apiVersion: apps/v1
kind: Deployment
metadata:
  name: portolio-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portolio
  template:
    metadata:
      labels:
        app: portolio
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
        - name: nginx-prometheus-exporter
          image: nginx/nginx-prometheus-exporter:1.4.0
          ports:
            - containerPort: 9113
          args:
            - "-telemetry.address" # not sure about this
            - "0.0.0.0:9113"       # not sure about this
            - "--nginx.scrape-uri=http://nginx:80/stub_status"
        - name: prometheus
          image: prom/prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
            - name: prometheus-storage
              mountPath: /prometheus
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
        - name: grafana
          image: grafana/grafana
          ports:
            - containerPort: 3000
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: prometheus-storage
          emptyDir: {}
