apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: portolio

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-prometheus-exporter
spec:
  ports:
    - port: 9113
      targetPort: 9113
  selector:
    app: portolio

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: portolio

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: portolio
