name: Test Nginx Server with Minikube

on:
  push:
    paths:
      - "version" # Trigger the workflow when the "version" file changes

jobs:
  test-nginx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: medyagh/local-dev-example-with-minikube

      - name: Start minikube
        uses: medyagh/setup-minikube@latest

      - name: Try the cluster!
        run: kubectl get pods -A

      - name: Build image
        run: |
          minikube image build -t portfolio:latest ${{ github.workspace }}/web/   
      
      - name: Deploy to minikube
        run: |
          ls
          minikube image ls
          kubectl apply -f ${{ github.workspace }}/minikube/nginx-deployment.yaml
          kubectl wait --for=condition=Ready pod -l app=nginx --timeout=60s

      - name: Run tests on Nginx
        run: |
          NODE_PORT=$(kubectl get svc nginx-service -o=jsonpath='{.spec.ports[0].nodePort}')
          echo "NodePort: ${NODE_PORT}"
          
          MINIKUBE_IP=$(minikube ip)
          echo "Minikube IP: ${MINIKUBE_IP}"

          # Test /en location
          curl -s -o /dev/null -w "%{http_code}" http://${MINIKUBE_IP}:${NODE_PORT}/en/ | grep -q "200" || exit 1
          echo "Nginx /en is accessible"

          # Test /fr location
          curl -s -o /dev/null -w "%{http_code}" http://${MINIKUBE_IP}:${NODE_PORT}/fr/ | grep -q "200" || exit 1
          echo "Nginx /fr is accessible"

      - name: Clean up Minikube
        run: |
          minikube delete