name: Test Nginx Server with Minikube

on:
  push:
    paths:
      - "version" # Trigger the workflow when the "version" file changes

jobs:
  test-nginx:
    runs-on: ubuntu-20.04

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t portfolio:latest ${GITHUB_WORKSPACE}/web/

      # Step 4: Install Minikube (manually)
      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/v1.31.2/minikube-linux-amd64
          sudo mv minikube-linux-amd64 /usr/local/bin/minikube
          sudo chmod +x /usr/local/bin/minikube

      # Step 5: Start Minikube
      - name: Start Minikube
        run: |
          minikube start --wait --driver=docker --kubernetes-version=v1.27.4
          minikube status

      # Step 6: Load Docker image into Minikube
      - name: Load Docker image into Minikube
        run: |
          minikube image load portfolio:latest

      # Step 7: Apply Kubernetes manifests
      - name: Apply ConfigMap and Deployment
        run: |
          kubectl apply -f ${GITHUB_WORKSPACE}/minikube/nginx-deployment.yaml
          kubectl wait --for=condition=available deployment/nginx-deployment --timeout=60s

      # Step 8: Expose the Nginx service (Minikube tunnel)
      - name: Expose Nginx Service
        run: |
          minikube tunnel &
          sleep 10

      # Step 9: Test Nginx server
      - name: Run tests on Nginx
        run: |
          # Get the exposed service IP
          NODE_PORT=$(kubectl get svc nginx-service -o=jsonpath='{.spec.ports[0].nodePort}')
          MINIKUBE_IP=$(minikube ip)

          # Test the /en location
          curl -s -o /dev/null -w "%{http_code}" http://${MINIKUBE_IP}:${NODE_PORT}/en/ | grep -q "200" || exit 1
          echo "Nginx /en is accessible"

          # Test the /fr location
          curl -s -o /dev/null -w "%{http_code}" http://${MINIKUBE_IP}:${NODE_PORT}/fr/ | grep -q "200" || exit 1
          echo "Nginx /fr is accessible"

      # Step 10: Clean up Minikube
      - name: Clean up Minikube
        run: |
          minikube delete --profile=minikube-test
