name: Test Nginx Server with Minikube

on:
  push:
    paths:
      - "version" # Trigger the workflow when the "version" file changes

jobs:
  test-nginx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Start minikube
        uses: medyagh/setup-minikube@latest

      - name: Build image
        run: |
          minikube image build -t portfolio:latest ${{ github.workspace }}/web/  
      
      - name: Deploy to minikube
        run: |
          kubectl apply -f ${{ github.workspace }}/minikube/nginx-config.yaml
          kubectl apply -f ${{ github.workspace }}/minikube/monitoring-deployment.yaml
          kubectl apply -f ${{ github.workspace }}/minikube/nginx-deployment.yaml
          sleep 10
          kubectl logs -l app=nginx
          kubectl wait --for=condition=Ready pod -l app=nginx --timeout=60s

      - name: Run tests on Nginx
        run: |
          NODE_PORT=$(kubectl get svc nginx-service -o=jsonpath='{.spec.ports[0].nodePort}')
          echo "NodePort: ${NODE_PORT}"
          
          MINIKUBE_IP=$(minikube ip)
          echo "Minikube IP: ${MINIKUBE_IP}"



          # Test /en location
          curl -s -o /dev/null -w "%{http_code}" http://${MINIKUBE_IP}:${NODE_PORT}/en/ | grep -q "200" || exit 1
          echo "Nginx /en is accessible"

          # Test /fr location
          curl -s -o /dev/null -w "%{http_code}" http://${MINIKUBE_IP}:${NODE_PORT}/fr/ | grep -q "200" || exit 1
          echo "Nginx /fr is accessible"

          # Test /grafana location
          echo "###################Check Minikube DNS Resolution###################"
          kubectl get pods -n kube-system -l k8s-app=coredns
          echo "###################Verify the Grafana Servicen###################"
          kubectl get svc -n default grafana
          kubectl get endpoints -n default grafana
          echo "###################Test DNS Resolution from a Pod##################"
          kubectl run -i --tty --rm debug --image=busybox --serviceaccount default --restart=Never -- nslookup grafana.default.svc.cluster.local
          echo "###################Check the CoreDNS ConfigMap###################"
          kubectl get configmap coredns -n kube-system -o yaml


          minikube ssh -- "nslookup grafana.default.svc.cluster.local"
          curl -s -o /dev/null -w "%{http_code}" http://${MINIKUBE_IP}:${NODE_PORT}/grafana/ | grep -q "200" || exit 1
          echo "Nginx /grafana is accessible"

      - name: Clean up Minikube
        run: |
          minikube delete